### ISSUE TITLE
User Story - Wine Price Data API

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/wine-price-api#2]
The end result of the wine price product will be to have a simple interface to historical wine price data that allows users to both investigate this data interactively, but also to download large components of the data for offline use.  This interface is primarily for  retrieving wine price data.  

# Tasks 

- [x] Update the api for a wine_price table
- [x] Include the Sherry Lehman Catalog as a startup for the Development 
- [x] Update this page with some examples
- [x] Include documentation #6 

## API 

Given the base URL for the system, (eg. http://wine.lib.ucdavis.edu/),  the following endpoints exist.

- ${BASE}/wine_prices/ = This will return an index of all the wine_price data.   By default, there will be a limit if 1000 entries returned, but the user can modify that behavior with the following parameters

-```?cou

### Per column quereis

for every column , ```{col}``` in : ```type | color | varietal | otherDesignation | brandName | winery_name | bootlleSize``` We have the following search parameters 

- ```?{col}_is_not_null``` Returns values where the column has data
- ```?{col}__starts_with=[text]``` The column starts with the given text
- ```?{col}__ends_with=[text]``` Column data ends with text.

For columns {col} in ```vintage_year | perPrice | casePrice | priceYear```, we include the following parameters: 

- ```?{col}__eq=number```
-```?{col}__gt(e?)=number``` is greater than (gt) or greater than or equal (gte) [number]
-```?{col}__lt(e?)=number```is less than (lt) or less than or equal (lte) [number]

In addition, users will be able to search on the various parameters ofthe 

## Wine Price Schema

This is basically, a single table, with a pointer back to the provenience of where the individual price items came from.  The columns of the wine-price table  is:

column | type | description
--- | --- | ---
id | serial | wine_price identifier
provenance_id  | integer | references provenance table
type | text | Wine Type (Still,Sparkling,Fortified) 
color | text | Wine Color (Red,White,Rose )
varietal  | text | Grape Variety 
otherDesignation | text | Other Wine type designation (eg. Rhone)
brandName | text | The brand of the wine
winery_name | text  | The winery where the bottle comes from
vintage_year | integer | The vintage of the wine
region | text | Where the wine comes from.  Currently not controlled
bottleSize | text | Type of bottle being sold Controlled vocabulary (piccelo,split,standard,half,magnum) 
perPrice | decimal | Price per Bottle
casePrice | decimal | Price per Case 
priceYear | integer | When this price was identified
